### ISSUE TITLE
Add Contact counter

### ISSUE THREAD

**Issue by christiano-git** [DP-3T/dp3t-app-ios#9]
I think It would be nice to Show a Counter to indicate the number of close contacts.

A over the Last 21 days
B as per day

It could get User Award how much the Exposé

**Comment by christiano-git** [comment]
> I think It would be nice to Show a Counter to indicate the number of close contacts.
> 
> A over the Last 21 days
> B as per Fax
> 
> It could get User Award how much the Exposé

**Comment by maerki** [comment]
We're discussing this with UX experts, but probably won't go in this direction right now. There are several reasons:
- There is no concept of "contact" (and it cannot exist by design) and counter of handshakes is hard to understand for users.
- The revealed information can be confusing or problematic.
- It's interesting for us developers but not that important for other users .

**Comment by christiano-git** [comment]
I understand that this might be not in the scope. However based on my experience in the IT sector for protection and supervision area in Europe I learned “user like to have a an indicator for 24/7 background application”.
There is a need to prove that the system is running. Let say you have a motorcycle with ABS. Yes there is a ABS light on while you turn on the engine. However the first ride in spring many driver go on a parking space to prove the ABS.
From my point of view it would gain acceptance of this App.
